In [18]:
import pandas as pd

In [19]:
df = pd.read_excel(r"D:\JafarShop\Scrapers\total\تحديث منتجات توتال-compressed - Copy.xlsx")

In [20]:
df2 = pd.read_excel(r"D:\JafarShop\Scrapers\total\upload_template_final (6).xlsx")

In [21]:
df

,Item No.,Picture,Unnamed: 2,Product name,Description & Features,Unit,Qty,Unnamed: 7,فرق,BAR CODE
0,TIWLI20135\n,NaN,درل شحن 20 Total TIWLI‏20135\nفولت 1350 نيوتن ...,Cordless impact wrench,Brushless motor\nVoltage: 20V Square drive: 3/...,PCS,20,165.00,210.0,6932584800551
1,TCKLI20273\n,NaN,+ طقم درل Total TCKLI‏20273\nصاروخ شحن م بطاري...,Cordless 2 pcs combo kit,Voltage: 20V\n1 Pcs cordless angle grinder(TAG...,SET,40,78.00,115.0,6942210227676
2,TAC2331853,NaN,Total TAC233185 خشب 4/1.7 انش 42 سن عدد 2 طقم ...,Ultra-thin TCT saw blade set,"Size: 185mm(7-1/4"") Teeth quantity: 24T Arbor:...",SET,150,4.00,5.5,6976057332484
3,TABLI200181,NaN,Total TABLI200181 Lithium- ion blower\nسرعات ب...,Cordless blower,Voltage:20V\nNo-load speed:0-9000/0-18000rpm M...,PCS,40,30.00,40.0,6941639835158
4,TWLI20881\n,NaN,لوكس شحن 20 Total TWLI‏20881\nفولت م بطارية وشاحن,Cordless work lamp,Voltage:20V\nLED power dissipation:22.5W Lumen...,PCS,40,40.00,50.0,6923736767136
...,...,...,...,...,...,...,...,...,...,...
100,THL013AAA6\n,NaN,Total THL013AAA6 Headlamp\nلوكس راس بطارية,Headlamp,Brightness: Max:200 lumens Low:100 lumens\nUs...,PCS,96,5.75,8.5,6941639853916
101,TSP12102,NaN,Total TSP12102 كفوف عمال خفيف,Nitrile gloves,Size:XL\nLiner Material:Polyester Coating mate...,PAIR,2400,0.40,0.7,6941639888482
102,THT1516301\n,NaN,Total THT1516301 22 مقص سياج\nانش,Hedge shear,"Head material: SK5 Length:23""(575mm)\nWavy bla...",PCS,240,6.45,9.0,6925582170009
103,THPS3308\n,NaN,Total THPS3308 منشار شجر 33 سم,Pruning saw,"Size:13""/330mm Material:Taiwan SK5 7TPI,heat t...",PCS,480,4.00,6.0,6923736765415
104,THHR20124,NaN,بكرة م بربيش Total THHR‏20124 متر و 6 قط كوبلي...,Hose reel set,"Hose reel set\nEquipped with 1pcs 20Mx1/2"" 3-p...",SET,60,22.50,33.0,6932584809608

In [22]:
df2.head()

,tags,Item No.,Unit,Qty,Unnamed: 7,فرق,Images,Product_URL,Brand,arabic description,product_title_ar,meta_title,meta_description,handle_ar
0,"tools,power-tools,drill,power-drill",TIWLI20135_x000D_\n,PCS,20,165.00,210.0,https://static.wixstatic.com/media/06303a_74c5...,https://www.total-jo.com/product-page/%D8%AF%D...,Total,اسم المنتج بالعربي: دريل بوكسات شحن 1350 نيوتن...,دريل بوكسات شحن 1350 نيوتن من Total بالفولتية ...,دريل بوكسات شحن 1350 نيوتن للاستخدام الآمن من ...,احصل على دريل بوكسات شحن 1350 نيوتن من توتال، ...,دريل-بوكسات-شحن-1350-نيوتن-من-Total-بالفولتية-...
1,"tools,power-tools,drill,power-drill",TCKLI20273_x000D_\n,SET,40,78.00,115.0,https://static.wixstatic.com/media/06303a_b399...,https://www.total-jo.com/product-page/%D8%B7%D...,Total,اسم المنتج بالعربي: طقم دريل وصاروخ شحن بدون أ...,طقم دريل وصاروخ شحن بدون أسلاك من توتال 20 فول...,طقم دريل وصاروخ شحن بدون أسلاك من توتال - safe...,احصل على طقم دريل وصاروخ شحن بدون أسلاك من توت...,طقم-دريل-وصاروخ-شحن-بدون-أسلاك-من-توتال-20-فول...
2,"tools,power-tools,blowers,blower-charge",TABLI200181,PCS,40,30.00,40.0,https://static.wixstatic.com/media/06303a_e375...,https://www.total-jo.com/product-page/%D8%A8%D...,Total,اسم المنتج بالعربي: بلور شحن 20 فولت من توتال ...,بلور شحن 20 فولت من توتال ببطارية ليثيوم أيوني...,بلور شحن 20 فولت لتنظيف فعال من توتال من جعفر ...,احصل على بلور الشحن 20 فولت من توتال ببطارية ل...,بلور-شحن-20-فولت-من-توتال-ببطارية-ليثيوم-أيوني...
3,"Electrical-appliances-L1,cleaning-appliances,v...",TVLI20126,PCS,40,33.00,50.0,https://static.wixstatic.com/media/06303a_0606...,https://www.total-jo.com/product-page/%D9%85%D...,Total,اسم المنتج بالعربي: مكنسة شحن 20 فولت توتال بب...,مكنسة شحن 20 فولت توتال ببطارية 2.0AH وقوة شفط...,مكنسة شحن 20 فولت توتال بقوة شفط قوية من جعفر ...,مكنسة شحن توتال 20 فولت تضمن تنظيفًا عميقًا بف...,مكنسة-شحن-20-فولت-توتال-ببطارية-20AH-وقوة-شفط-...
4,"tools,power-tools-accessories,Batteries-and-ch...",TFBLI20011_x000D_\n,PCS,100,12.75,18.0,https://static.wixstatic.com/media/06303a_6ca2...,https://www.total-jo.com/product-page/%D8%A8%D...,Total,اسم المنتج بالعربي: بطارية 20 فولت 2 أمبير ليث...,بطارية 20 فولت 2 أمبير ليثيوم توتال مع مؤشر LE...,بطارية ليثيوم 20 فولت 2 أمبير مع مؤشر LED من ج...,احصل على بطارية ليثيوم 20 فولت 2 أمبير من Tota...,بطارية-20-فولت-2-أمبير-ليثيوم-توتال-مع-مؤشر-LE...

In [39]:
cols= ['Item No.','BAR CODE']

df = df[cols].astype(str)

df

        Item No.       BAR CODE
0     TIWLI20135  6932584800551
1     TCKLI20273  6942210227676
2     TAC2331853  6976057332484
3    TABLI200181  6941639835158
4      TWLI20881  6923736767136
..           ...            ...
100   THL013AAA6  6941639853916
101     TSP12102  6941639888482
102   THT1516301  6925582170009
103     THPS3308  6923736765415
104    THHR20124  6932584809608

[105 rows x 2 columns]

In [42]:
merged_df = pd.merge(df, df2, on='Item No.')

In [ ]:
merged_df.head()

,Item No.,BAR CODE,tags,Unit,Qty,Unnamed: 7,فرق,Images,Product_URL,Brand,arabic description,product_title_ar,meta_title,meta_description,handle_ar
0,TIWLI20135,6932584800551,"tools,power-tools,drill,power-drill",PCS,20,165.00,210.0,https://static.wixstatic.com/media/06303a_74c5...,https://www.total-jo.com/product-page/%D8%AF%D...,Total,اسم المنتج بالعربي: دريل بوكسات شحن 1350 نيوتن...,دريل بوكسات شحن 1350 نيوتن من Total بالفولتية ...,دريل بوكسات شحن 1350 نيوتن للاستخدام الآمن من ...,احصل على دريل بوكسات شحن 1350 نيوتن من توتال، ...,دريل-بوكسات-شحن-1350-نيوتن-من-Total-بالفولتية-...
1,TCKLI20273,6942210227676,"tools,power-tools,drill,power-drill",SET,40,78.00,115.0,https://static.wixstatic.com/media/06303a_b399...,https://www.total-jo.com/product-page/%D8%B7%D...,Total,اسم المنتج بالعربي: طقم دريل وصاروخ شحن بدون أ...,طقم دريل وصاروخ شحن بدون أسلاك من توتال 20 فول...,طقم دريل وصاروخ شحن بدون أسلاك من توتال - safe...,احصل على طقم دريل وصاروخ شحن بدون أسلاك من توت...,طقم-دريل-وصاروخ-شحن-بدون-أسلاك-من-توتال-20-فول...
2,TABLI200181,6941639835158,"tools,power-tools,blowers,blower-charge",PCS,40,30.00,40.0,https://static.wixstatic.com/media/06303a_e375...,https://www.total-jo.com/product-page/%D8%A8%D...,Total,اسم المنتج بالعربي: بلور شحن 20 فولت من توتال ...,بلور شحن 20 فولت من توتال ببطارية ليثيوم أيوني...,بلور شحن 20 فولت لتنظيف فعال من توتال من جعفر ...,احصل على بلور الشحن 20 فولت من توتال ببطارية ل...,بلور-شحن-20-فولت-من-توتال-ببطارية-ليثيوم-أيوني...
3,TVLI20126,6976057331210,"Electrical-appliances-L1,cleaning-appliances,v...",PCS,40,33.00,50.0,https://static.wixstatic.com/media/06303a_0606...,https://www.total-jo.com/product-page/%D9%85%D...,Total,اسم المنتج بالعربي: مكنسة شحن 20 فولت توتال بب...,مكنسة شحن 20 فولت توتال ببطارية 2.0AH وقوة شفط...,مكنسة شحن 20 فولت توتال بقوة شفط قوية من جعفر ...,مكنسة شحن توتال 20 فولت تضمن تنظيفًا عميقًا بف...,مكنسة-شحن-20-فولت-توتال-ببطارية-20AH-وقوة-شفط-...
4,TFBLI20011,6941639818007,"tools,power-tools-accessories,Batteries-and-ch...",PCS,100,12.75,18.0,https://static.wixstatic.com/media/06303a_6ca2...,https://www.total-jo.com/product-page/%D8%A8%D...,Total,اسم المنتج بالعربي: بطارية 20 فولت 2 أمبير ليث...,بطارية 20 فولت 2 أمبير ليثيوم توتال مع مؤشر LE...,بطارية ليثيوم 20 فولت 2 أمبير مع مؤشر LED من ج...,احصل على بطارية ليثيوم 20 فولت 2 أمبير من Tota...,بطارية-20-فولت-2-أمبير-ليثيوم-توتال-مع-مؤشر-LE...